import type { VercelRequest, VercelResponse } from '@vercel/node';
import { requireUser } from '../lib/auth';
import { getEnv } from '../lib/env';
import { badRequest, methodNotAllowed, ok, serverError } from '../lib/response';
import { apiError } from '@tmp/shared';
import { z } from 'zod';

const questionSchema = z.object({
  prompt: z.string().min(5).max(1000),
});

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') return methodNotAllowed(res);

  try {
    await requireUser(req);

    const parsed = questionSchema.safeParse(req.body);
    if (!parsed.success) {
      return badRequest(res, apiError('INVALID_INPUT', 'INVALID_INPUT', parsed.error.flatten()));
    }

    const { prompt } = parsed.data;

    // Call Groq AI API
    const apiKey = getEnv('GROQ_API_KEY');
    
    const systemPrompt = `You are AI Noor, an Islamic knowledge assistant. Provide accurate, respectful, and well-sourced answers about Islam. 
Always emphasize that your responses are for educational purposes and that users should consult qualified scholars for fiqh and personal matters.
Be concise, clear, and cite relevant Islamic sources when possible.`;

    const groqResponse = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'llama-3.1-70b-versatile', // Groq's fast model
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: prompt },
        ],
        temperature: 0.7,
        max_tokens: 1000,
      }),
    });

    if (!groqResponse.ok) {
      const errorData = await groqResponse.json().catch(() => ({}));
      console.error('Groq API error:', errorData);
      throw new Error('AI service unavailable');
    }

    const groqData = await groqResponse.json() as {
      choices?: Array<{ message?: { content?: string } }>;
    };

    const answer = groqData.choices?.[0]?.message?.content || 
      'I apologize, but I was unable to generate a response. Please try again.';

    ok(res, {
      answer,
      disclaimer:
        'Responses are generated by AI based on general Islamic sources and may be inaccurate. This is an assistive tool and does not replace qualified scholarship. Please verify with trusted scholars for fiqh and personal matters.',
    });
  } catch (error) {
    console.error('ai-noor error', error);
    if ((error as Error).message === 'UNAUTHORIZED') {
      return badRequest(res, apiError('UNAUTHORIZED', 'UNAUTHORIZED'));
    }
    if ((error as Error).message === 'AI service unavailable') {
      return serverError(res);
    }
    badRequest(res, apiError('AI_NOOR_UNAVAILABLE', 'AI_NOOR_UNAVAILABLE'));
  }
}



